# Generated by Django 5.2.17 on 2026-10-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sample_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional price for exactly the sample quantity.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sample_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
