# Generated by Django 5.2.17 on 2026-10-09 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_category_icon_remove_product_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name shown in admin.', max_length=120)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('headline', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('button_label', models.CharField(default='Explore products', max_length=40)),
                ('button_target', models.CharField(choices=[('products', 'Product catalogue'), ('categories', 'Shop categories'), ('quote', 'Request a bulk quote'), ('product', 'A specific product')], default='products', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, help_text='Required when the button targets a specific product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_campaigns', to='core.product')),
            ],
            options={
                'verbose_name': 'promotion campaign',
                'verbose_name_plural': 'promotion campaigns',
                'ordering': ['sort_order', '-id'],
            },
        ),
    ]
