# Generated by Django 5.2.17 on 2026-10-09 15:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_visible_detail_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting seller confirmation'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('additional_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='core.product')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'name'), name='unique_product_customization_name')],
            },
        ),
        migrations.CreateModel(
            name='ProductPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('maximum_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='core.product')),
            ],
            options={
                'ordering': ['minimum_quantity'],
                'constraints': [models.UniqueConstraint(fields=('product', 'minimum_quantity'), name='unique_product_price_tier_start'), models.CheckConstraint(condition=models.Q(('maximum_quantity__isnull', True), ('maximum_quantity__gte', models.F('minimum_quantity')), _connector='OR'), name='product_price_tier_valid_range')],
            },
        ),
    ]
