# Generated by Django 5.2.17 on 2026-10-09 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sellerorder_status_productcustomization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='core.sellerprofile'),
        ),
    ]
