# Generated by Django 5.2.17 on 2026-10-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_paymentwebhookevent_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerorder',
            name='package_height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='sellerorder',
            name='package_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='sellerorder',
            name='package_weight_grams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerorder',
            name='package_width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
