# Generated by Django 5.2.17 on 2026-10-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sellerorder_package_height_cm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('offline_pending', 'Awaiting offline payment'), ('pending', 'Payment pending'), ('captured', 'Paid'), ('failed', 'Payment failed'), ('refunded', 'Refunded')], default='offline_pending', max_length=20),
        ),
    ]
