# Generated by Django 5.2.17 on 2026-10-10 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_product_shipping_height_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='accent_color',
            field=models.CharField(default='#B99A62', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color, such as #B99A62.')]),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='brand_icon',
            field=models.CharField(choices=[('bi-box-seam', 'Box'), ('bi-bag', 'Bag'), ('bi-shop', 'Shop'), ('bi-buildings', 'Buildings'), ('bi-leaf', 'Leaf'), ('bi-stars', 'Stars')], default='bi-box-seam', max_length=40),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='browser_title',
            field=models.CharField(default='SupplyHub | Business Wholesale Marketplace', max_length=160),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='hero_eyebrow',
            field=models.CharField(default='YOUR BUSINESS SOURCING PARTNER', max_length=80),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='hero_headline',
            field=models.CharField(default='Wholesale sourcing, made simple.', max_length=180),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='page_background_color',
            field=models.CharField(default='#F6F5F2', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color, such as #F6F5F2.')]),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='primary_color',
            field=models.CharField(default='#0F766E', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color, such as #0F766E.')]),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='primary_dark_color',
            field=models.CharField(default='#134E4A', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color, such as #134E4A.')]),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='text_color',
            field=models.CharField(default='#172025', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color, such as #172025.')]),
        ),
    ]
